#!/usr/bin/env bash

# Delete first 14 characters (vscode://file/)
request=${1:14}

# Decode URL
request=$(echo $request | echo -e "$(sed 's/+/ /g; s/%/\\x/g')")

# Replace &line= with :
request=${request/&line=/:}

# Launch Visual Studio Code
/usr/bin/code -g -r $request
